"""Master Test Suite for Sprint 13 — Report & Export Engines.

Verifies end-to-end functionality for:
  * Sprint 13.1: Unified Report Engine
  * Sprint 13.2: PDF Report Generation (ReportLab)
  * Sprint 13.3: CSV Data Export
  * Sprint 13.5: Integration API Endpoints (401, 404, 200 OK)
"""

from __future__ import annotations

import os
import sys
import time
from pathlib import Path

BACKEND = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND))

os.environ["APP_ENV"] = "test"
os.environ["DATABASE_URL"] = "sqlite:///" + str(BACKEND / "atlas_ai.db").replace("\\", "/")
os.environ["JWT_SECRET_KEY"] = "test-secret-32-bytes-long-key-12345"

from fastapi.testclient import TestClient
from app.main import app
from app.models.user import User
from app.repositories.business_repository import BusinessNotFound, BusinessRepository
from app.services.csv_export_service import CsvExportService
from app.services.pdf_report_service import PdfReportService
from app.services.report_service import ReportService
from app.utils.database import Base, SessionLocal, engine

Base.metadata.create_all(bind=engine)


def test_sprint13_services_unit():
    db = SessionLocal()
    try:
        ts = int(time.time())
        user = User(
            email=f"reportuser_{ts}@example.com",
            password_hash="hash",
            full_name="Report Test User",
        )
        db.add(user)
        db.commit()
        db.refresh(user)

        repo = BusinessRepository(db)
        service = ReportService(repo)

        # 1. Empty profile -> raises BusinessNotFound
        raised = False
        try:
            service.compute(user.id)
        except BusinessNotFound:
            raised = True
        assert raised, "[FAIL] Expected BusinessNotFound when profile does not exist"

        # 2. Create business profile
        biz = repo.create(
            owner_id=user.id,
            legal_name="Apex Report Logistics",
            industry="Supply Chain",
            established_year=2021,
            employee_count=16,
            annual_revenue=520000.0,
            revenue_currency="USD",
            country="US",
            state_region="Illinois",
            city="Chicago",
        )
        db.commit()

        fresh = repo.get_by_owner(user.id)
        assert fresh is not None

        # 3. Unified Report Service
        unified = service.generate_unified_report(fresh)
        assert unified.executive_summary.business_name == "Apex Report Logistics"
        assert unified.executive_summary.overall_health_score > 0
        assert len(unified.recommendations.recommendations) > 0

        # 4. PDF Report Service
        pdf_service = PdfReportService(repo)
        pdf_bytes = pdf_service.generate_pdf_report(fresh, report_type="executive")
        assert len(pdf_bytes) > 0
        assert pdf_bytes.startswith(b"%PDF-"), "[FAIL] Generated bytes do not start with %PDF-"

        # 5. CSV Export Service
        csv_service = CsvExportService(repo)
        csv_str = csv_service.generate_csv_export(fresh)
        assert len(csv_str) > 0
        assert "Apex Report Logistics" in csv_str
        assert "KEY PERFORMANCE INDICATORS" in csv_str

        print("[PASS] Sprint 13 Unit Services passed cleanly!")

    finally:
        db.close()


def test_sprint13_api_integration():
    client = TestClient(app)
    ts = int(time.time())

    # 1. Unauthenticated -> 401
    for ep in ["/api/v1/reports/unified", "/api/v1/reports/pdf", "/api/v1/reports/csv"]:
        res = client.get(ep)
        assert res.status_code == 401, f"[FAIL] {ep} expected 401, got {res.status_code}"

    # 2. Register user without business -> 404
    email_empty = f"rep_empty_{ts}@example.com"
    client.post(
        "/api/v1/auth/register",
        json={"full_name": "Empty User", "email": email_empty, "password": "Password123!"},
    )
    login_empty = client.post(
        "/api/v1/auth/login",
        json={"email": email_empty, "password": "Password123!"},
    )
    for ep in ["/api/v1/reports/unified", "/api/v1/reports/pdf", "/api/v1/reports/csv"]:
        res = client.get(ep, cookies=login_empty.cookies)
        assert res.status_code == 404, f"[FAIL] {ep} expected 404, got {res.status_code}"

    # 3. Register user with business -> 200 OK
    email_biz = f"rep_biz_{ts}@example.com"
    client.post(
        "/api/v1/auth/register",
        json={"full_name": "Report Biz User", "email": email_biz, "password": "Password123!"},
    )
    login_biz = client.post(
        "/api/v1/auth/login",
        json={"email": email_biz, "password": "Password123!"},
    )
    cookies = login_biz.cookies

    biz_payload = {
        "basic": {
            "legal_name": "Apex Unified Report Corp",
            "industry": "Clean Energy",
            "established_year": 2018,
            "employee_count": 28,
            "annual_revenue": 950000.0,
            "revenue_currency": "USD",
        }
    }
    client.post("/api/v1/business", json=biz_payload, cookies=cookies)

    # Test /api/v1/reports/unified
    res_unified = client.get("/api/v1/reports/unified", cookies=cookies)
    assert res_unified.status_code == 200
    assert "report" in res_unified.json()

    # Test /api/v1/reports/pdf
    res_pdf = client.get("/api/v1/reports/pdf", cookies=cookies)
    assert res_pdf.status_code == 200
    assert res_pdf.headers["content-type"] == "application/pdf"
    assert res_pdf.content.startswith(b"%PDF-")

    # Test /api/v1/reports/csv
    res_csv = client.get("/api/v1/reports/csv", cookies=cookies)
    assert res_csv.status_code == 200
    assert "text/csv" in res_csv.headers["content-type"]
    assert "Apex Unified Report Corp" in res_csv.text

    print("[PASS] Sprint 13 Integration API test suite passed cleanly!")


if __name__ == "__main__":
    test_sprint13_services_unit()
    test_sprint13_api_integration()
